version: '2'

networks:
  youth4planet:

services:
  ca_y4p2:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.y4p2.youth4planet.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=8054
    ports:
      - "8054:8054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./fabric-ca/y4p2:/etc/hyperledger/fabric-ca-server
    container_name: ca.y4p2.youth4planet.com
    hostname: ca.y4p2.youth4planet.com
    networks:
      - youth4planet
