OrdererOrgs:

  - Name: Orderer
    Domain: youth4planet.com
    EnableNodeOUs: true

    Specs:
      - Hostname: orderer
        SANS:
          - "localhost"
          - "127.0.0.1"

PeerOrgs:

  - Name: y4p1
    Domain: y4p1.youth4planet.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1

  - Name: y4p2
    Domain: y4p2.youth4planet.com
    EnableNodeOUs: true

    Template:
      Count: 2
      SANS:
        - "localhost"

    Users:
      Count: 1